name: future_or
description: A collection of widgets, methods and extention methods that make working with FutureOr objects easier.
version: 0.1.0
author: Aligator <Ali.gh2236@gmail.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter